exclude: [guidelines.md,  "Gemfile", "Gemfile.lock", README.adoc, "_docs/code-snippets", "_docs/includes", '*.sh']
attrs: &asciidoc_attributes
  version: '2.8.1'
  base_url: /docs
  stylesdir: /docs/assets/css
  imagesdir: /docs/{version}
  source-highlighter: rouge
  table-stripes: even
  javadoc_base_url: https://ignite.apache.org/releases/{version}/javadoc
  javaCodeDir: code-snippets/java/src/main/java/org/apache/ignite/snippets
  githubUrl: https://github.com/apache/ignite/tree/master
collections:
  docs:
    permalink: /docs/2.8.1/:path:output_ext
    output: true
defaults:
  -
    scope:
      path: ''
    values:
      layout: 'doc'
  -
    scope:
      path: '_docs'
    values:
      toc: ignite 
asciidoctor:
  base_dir: _docs/ 
  attributes: *asciidoc_attributes
   
